global:
  scrape_interval: 10s

rule_files:
  - '/etc/prometheus/rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'localhost:9093'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      - labels:
          name: 'Prometheus'
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.19.139:9100']
      - labels:
          name: 'prod-db-cdp-server'
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        regex:  '(.*)'             # This is the default value.
        target_label: 'instance'
        replacement: 'prod-db-cdp-server'   # Have to specify a port too.
  - job_name: 'alertmanager'
    scrape_interval: 5s
    static_configs: 
      - targets: ['localhost:9093']
      - labels:
          name: 'AlertManager'
